// GENERATED — run: python3 tool/generate_supernova_components.py

/// How a Supernova Figma component is represented in Flutter.
enum SupernovaComponentKind {
  /// Hand-written Flutter widget in this package.
  widget,

  /// Static asset library (SVG/PNG in assets/).
  asset,

  /// Figma layout template — compose with other widgets.
  template,
}

/// Maps a Supernova component name to its Flutter representation.
class SupernovaComponentEntry {
  const SupernovaComponentEntry({
    required this.supernovaName,
    required this.kind,
    this.flutterWidget,
  });

  final String supernovaName;
  final SupernovaComponentKind kind;
  final String? flutterWidget;
}

/// All top-level Supernova / Figma components in design system 839081.
abstract final class SupernovaComponentRegistry {
  static const List<SupernovaComponentEntry> all = [
    SupernovaComponentEntry(supernovaName: '.Card footer', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: '.Card header', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: '.Legend', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: '.Side menu header', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: '7', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: 'Accordion', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAccordion'),
    SupernovaComponentEntry(supernovaName: 'Action-item', kind: SupernovaComponentKind.widget, flutterWidget: 'YakActionItem'),
    SupernovaComponentEntry(supernovaName: 'Actions', kind: SupernovaComponentKind.widget, flutterWidget: 'YakActions'),
    SupernovaComponentEntry(supernovaName: 'Additional-service', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAdditionalService'),
    SupernovaComponentEntry(supernovaName: 'address-picker', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAddressPicker'),
    SupernovaComponentEntry(supernovaName: 'Alert', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAlert'),
    SupernovaComponentEntry(supernovaName: 'Anatomy Dot', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Android', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Avatar', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAvatar'),
    SupernovaComponentEntry(supernovaName: 'Avatar & description', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAvatarDescription'),
    SupernovaComponentEntry(supernovaName: 'Avatar group', kind: SupernovaComponentKind.widget, flutterWidget: 'YakAvatarGroup'),
    SupernovaComponentEntry(supernovaName: 'Badge', kind: SupernovaComponentKind.widget, flutterWidget: 'YakBadge'),
    SupernovaComponentEntry(supernovaName: 'Bank Logos', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Banner', kind: SupernovaComponentKind.widget, flutterWidget: 'YakBanner'),
    SupernovaComponentEntry(supernovaName: 'bottom-navigation', kind: SupernovaComponentKind.widget, flutterWidget: 'YakBottomNavigation'),
    SupernovaComponentEntry(supernovaName: 'BottomSheet', kind: SupernovaComponentKind.widget, flutterWidget: 'YakBottomSheet'),
    SupernovaComponentEntry(supernovaName: 'Breadcrumb', kind: SupernovaComponentKind.widget, flutterWidget: 'YakBreadcrumb'),
    SupernovaComponentEntry(supernovaName: 'Button', kind: SupernovaComponentKind.widget, flutterWidget: 'YakButton'),
    SupernovaComponentEntry(supernovaName: 'Button Close', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCloseButton'),
    SupernovaComponentEntry(supernovaName: 'Button group', kind: SupernovaComponentKind.widget, flutterWidget: 'YakButtonGroup'),
    SupernovaComponentEntry(supernovaName: 'Button Love', kind: SupernovaComponentKind.widget, flutterWidget: 'YakLoveButton'),
    SupernovaComponentEntry(supernovaName: 'Calendar', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCalendar'),
    SupernovaComponentEntry(supernovaName: 'Calendar Dropdown', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCalendarDropdown'),
    SupernovaComponentEntry(supernovaName: 'Card-FinanceSummary', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCardFinanceSummary'),
    SupernovaComponentEntry(supernovaName: 'Card-Message', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCardMessage'),
    SupernovaComponentEntry(supernovaName: 'Card-progress', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCardProgress'),
    SupernovaComponentEntry(supernovaName: 'Card-Transaction', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCardTransaction'),
    SupernovaComponentEntry(supernovaName: 'Card-Transfer', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCardTransfer'),
    SupernovaComponentEntry(supernovaName: 'carousel', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCarousel'),
    SupernovaComponentEntry(supernovaName: 'Chart', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Chat', kind: SupernovaComponentKind.widget, flutterWidget: 'YakChatBubble'),
    SupernovaComponentEntry(supernovaName: 'Chat-Category', kind: SupernovaComponentKind.widget, flutterWidget: 'YakChatCategory'),
    SupernovaComponentEntry(supernovaName: 'Checkbox', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCheckbox'),
    SupernovaComponentEntry(supernovaName: 'Checkbox group', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCheckboxGroup'),
    SupernovaComponentEntry(supernovaName: 'chip', kind: SupernovaComponentKind.widget, flutterWidget: 'YakChip'),
    SupernovaComponentEntry(supernovaName: 'Color', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Comment', kind: SupernovaComponentKind.widget, flutterWidget: 'YakComment'),
    SupernovaComponentEntry(supernovaName: 'Component 1', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: 'Component Icon', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'confirm-delegate', kind: SupernovaComponentKind.widget, flutterWidget: 'YakConfirmDelegate'),
    SupernovaComponentEntry(supernovaName: 'Country', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCountrySelect'),
    SupernovaComponentEntry(supernovaName: 'Credit Banner Balance', kind: SupernovaComponentKind.widget, flutterWidget: 'YakCreditBannerBalance'),
    SupernovaComponentEntry(supernovaName: 'Detail-expand', kind: SupernovaComponentKind.widget, flutterWidget: 'YakDetailExpand'),
    SupernovaComponentEntry(supernovaName: 'Display Date', kind: SupernovaComponentKind.widget, flutterWidget: 'YakDisplayDate'),
    SupernovaComponentEntry(supernovaName: 'Display Icon', kind: SupernovaComponentKind.widget, flutterWidget: 'YakDisplayIcon'),
    SupernovaComponentEntry(supernovaName: 'Divider stepper', kind: SupernovaComponentKind.widget, flutterWidget: 'YakDividerStepper'),
    SupernovaComponentEntry(supernovaName: 'Document Action-item', kind: SupernovaComponentKind.widget, flutterWidget: 'YakDocumentActionItem'),
    SupernovaComponentEntry(supernovaName: 'Document-state', kind: SupernovaComponentKind.widget, flutterWidget: 'YakDocumentState'),
    SupernovaComponentEntry(supernovaName: 'Earning-progress', kind: SupernovaComponentKind.widget, flutterWidget: 'YakEarningProgress'),
    SupernovaComponentEntry(supernovaName: 'Earning-rate', kind: SupernovaComponentKind.widget, flutterWidget: 'YakEarningRate'),
    SupernovaComponentEntry(supernovaName: 'Earning-Type', kind: SupernovaComponentKind.widget, flutterWidget: 'YakEarningType'),
    SupernovaComponentEntry(supernovaName: 'EarningActivityCard', kind: SupernovaComponentKind.widget, flutterWidget: 'YakEarningActivityCard'),
    SupernovaComponentEntry(supernovaName: 'EarningSummary', kind: SupernovaComponentKind.widget, flutterWidget: 'YakEarningSummary'),
    SupernovaComponentEntry(supernovaName: 'element', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Feature-card', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFeatureCard'),
    SupernovaComponentEntry(supernovaName: 'Feature-comment', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFeatureComment'),
    SupernovaComponentEntry(supernovaName: 'Feature-Progress', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFeatureProgress'),
    SupernovaComponentEntry(supernovaName: 'Feature-vote-CTA', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFeatureVoteCta'),
    SupernovaComponentEntry(supernovaName: 'File extensions icon', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'File Upload', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFileUpload'),
    SupernovaComponentEntry(supernovaName: 'filter-chip', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFilterChip'),
    SupernovaComponentEntry(supernovaName: 'FinanceSummary', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFinanceSummary'),
    SupernovaComponentEntry(supernovaName: 'FooterSheet', kind: SupernovaComponentKind.widget, flutterWidget: 'YakFooterSheet'),
    SupernovaComponentEntry(supernovaName: 'Freame Icon', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Headline', kind: SupernovaComponentKind.widget, flutterWidget: 'YakHeadline'),
    SupernovaComponentEntry(supernovaName: 'hint text', kind: SupernovaComponentKind.widget, flutterWidget: 'YakHintText'),
    SupernovaComponentEntry(supernovaName: 'home-indicator', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'hourglass', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Icon', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Icon Button', kind: SupernovaComponentKind.widget, flutterWidget: 'YakIconButton'),
    SupernovaComponentEntry(supernovaName: 'ID Card', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'illustration', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'image', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Incentive', kind: SupernovaComponentKind.widget, flutterWidget: 'YakIncentive'),
    SupernovaComponentEntry(supernovaName: 'Indicator', kind: SupernovaComponentKind.widget, flutterWidget: 'YakIndicator'),
    SupernovaComponentEntry(supernovaName: 'Input field', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTextField'),
    SupernovaComponentEntry(supernovaName: 'Input Text area', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTextArea'),
    SupernovaComponentEntry(supernovaName: 'Input Verification code', kind: SupernovaComponentKind.widget, flutterWidget: 'YakVerificationCodeInput'),
    SupernovaComponentEntry(supernovaName: 'iOS-push-notifications', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'iPhone', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Job-type', kind: SupernovaComponentKind.widget, flutterWidget: 'YakJobType'),
    SupernovaComponentEntry(supernovaName: 'Label', kind: SupernovaComponentKind.widget, flutterWidget: 'YakLabel'),
    SupernovaComponentEntry(supernovaName: 'location', kind: SupernovaComponentKind.widget, flutterWidget: 'YakLocationPicker'),
    SupernovaComponentEntry(supernovaName: 'logo-app', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Map Pointer', kind: SupernovaComponentKind.widget, flutterWidget: 'YakMapPointer'),
    SupernovaComponentEntry(supernovaName: 'Mobile Segmented Control', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSegmentedControl'),
    SupernovaComponentEntry(supernovaName: 'MobileScreenTemplate', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Modal', kind: SupernovaComponentKind.widget, flutterWidget: 'YakModal'),
    SupernovaComponentEntry(supernovaName: 'Modal BG', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Notification', kind: SupernovaComponentKind.widget, flutterWidget: 'YakNotification'),
    SupernovaComponentEntry(supernovaName: 'Notification-Card', kind: SupernovaComponentKind.widget, flutterWidget: 'YakNotificationCard'),
    SupernovaComponentEntry(supernovaName: 'Pagination', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPagination'),
    SupernovaComponentEntry(supernovaName: 'Parcel-type', kind: SupernovaComponentKind.widget, flutterWidget: 'YakParcelType'),
    SupernovaComponentEntry(supernovaName: 'Password indicator', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPasswordIndicator'),
    SupernovaComponentEntry(supernovaName: 'Payment', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPaymentMethod'),
    SupernovaComponentEntry(supernovaName: 'Payment Logos', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'payment-fail', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPaymentFail'),
    SupernovaComponentEntry(supernovaName: 'Payout-expand', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPayoutExpand'),
    SupernovaComponentEntry(supernovaName: 'Payout-state', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPayoutState'),
    SupernovaComponentEntry(supernovaName: 'Phone Number', kind: SupernovaComponentKind.widget, flutterWidget: 'YakPhoneNumberField'),
    SupernovaComponentEntry(supernovaName: 'Pie Chart', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'placement', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'placement', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'process', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProcessStatus'),
    SupernovaComponentEntry(supernovaName: 'processCard', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProcessCard'),
    SupernovaComponentEntry(supernovaName: 'Profile-rider', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProfileRider'),
    SupernovaComponentEntry(supernovaName: 'progress', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProgress'),
    SupernovaComponentEntry(supernovaName: 'Progress bar', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProgressBar'),
    SupernovaComponentEntry(supernovaName: 'Progress circle', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProgressCircle'),
    SupernovaComponentEntry(supernovaName: 'Progress semicircle', kind: SupernovaComponentKind.widget, flutterWidget: 'YakProgressSemicircle'),
    SupernovaComponentEntry(supernovaName: 'Project status', kind: SupernovaComponentKind.template),
    SupernovaComponentEntry(supernovaName: 'Rating', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRating'),
    SupernovaComponentEntry(supernovaName: 'Rating', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRating'),
    SupernovaComponentEntry(supernovaName: 'Rating', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRating'),
    SupernovaComponentEntry(supernovaName: 'Rating-Chip', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRatingChip'),
    SupernovaComponentEntry(supernovaName: 'referral-bonus', kind: SupernovaComponentKind.widget, flutterWidget: 'YakReferralBonus'),
    SupernovaComponentEntry(supernovaName: 'referral-code-card', kind: SupernovaComponentKind.widget, flutterWidget: 'YakReferralCodeCard'),
    SupernovaComponentEntry(supernovaName: 'referral-stepper', kind: SupernovaComponentKind.widget, flutterWidget: 'YakReferralStepper'),
    SupernovaComponentEntry(supernovaName: 'Result-State', kind: SupernovaComponentKind.widget, flutterWidget: 'YakResultState'),
    SupernovaComponentEntry(supernovaName: 'RichtextEditor', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRichTextEditor'),
    SupernovaComponentEntry(supernovaName: 'RichtextToolbar', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRichTextToolbar'),
    SupernovaComponentEntry(supernovaName: 'Rider-type', kind: SupernovaComponentKind.widget, flutterWidget: 'YakRiderType'),
    SupernovaComponentEntry(supernovaName: 'Scroll bar', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Search', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSearchField'),
    SupernovaComponentEntry(supernovaName: 'Search Action', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSearchAction'),
    SupernovaComponentEntry(supernovaName: 'Search Display', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSearchDisplay'),
    SupernovaComponentEntry(supernovaName: 'Section-Header', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSectionHeader'),
    SupernovaComponentEntry(supernovaName: 'Selector-Group', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSelectorGroup'),
    SupernovaComponentEntry(supernovaName: 'Selects', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSelect'),
    SupernovaComponentEntry(supernovaName: 'Slider', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSlider'),
    SupernovaComponentEntry(supernovaName: 'Social button groups', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSocialButtonGroup'),
    SupernovaComponentEntry(supernovaName: 'Social platforms logos', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'status-bar', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Stepper', kind: SupernovaComponentKind.widget, flutterWidget: 'YakStepper'),
    SupernovaComponentEntry(supernovaName: 'Steps', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSteps'),
    SupernovaComponentEntry(supernovaName: 'Swipe left action', kind: SupernovaComponentKind.widget, flutterWidget: 'YakSwipeAction'),
    SupernovaComponentEntry(supernovaName: 'Tabs', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTabs'),
    SupernovaComponentEntry(supernovaName: 'Text Icon', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Thumbnail', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Tile', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTile'),
    SupernovaComponentEntry(supernovaName: 'Title', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTitle'),
    SupernovaComponentEntry(supernovaName: 'Title-Progress', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTitleProgress'),
    SupernovaComponentEntry(supernovaName: 'Toggle', kind: SupernovaComponentKind.widget, flutterWidget: 'YakToggle'),
    SupernovaComponentEntry(supernovaName: 'Tool tip', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTooltip'),
    SupernovaComponentEntry(supernovaName: 'top-navigation', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTopNavigation'),
    SupernovaComponentEntry(supernovaName: 'TransferStatus', kind: SupernovaComponentKind.widget, flutterWidget: 'YakTransferStatus'),
    SupernovaComponentEntry(supernovaName: 'User-comment-card', kind: SupernovaComponentKind.widget, flutterWidget: 'YakUserCommentCard'),
    SupernovaComponentEntry(supernovaName: 'Vehicle', kind: SupernovaComponentKind.widget, flutterWidget: 'YakVehicleCard'),
    SupernovaComponentEntry(supernovaName: 'Vehicle', kind: SupernovaComponentKind.widget, flutterWidget: 'YakVehicleCard'),
    SupernovaComponentEntry(supernovaName: 'Venn Chart', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Video Call UI', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'Video player', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'World map', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'YAK-Expression', kind: SupernovaComponentKind.asset),
    SupernovaComponentEntry(supernovaName: 'YAK-Poses', kind: SupernovaComponentKind.asset),
  ];

  static SupernovaComponentEntry? find(String supernovaName) {
    for (final entry in all) {
      if (entry.supernovaName == supernovaName) return entry;
    }
    return null;
  }

  static List<SupernovaComponentEntry> get widgets =>
      all.where((e) => e.kind == SupernovaComponentKind.widget).toList();

  static List<SupernovaComponentEntry> get assets =>
      all.where((e) => e.kind == SupernovaComponentKind.asset).toList();
}
